#!/usr/bin/env ruby
# frozen_string_literal: true

ENV["BUNDLE_GEMFILE"] ||= File.expand_path("./Gemfile", __dir__)
require "bundler/setup"
require "rack"
options = {
  config: File.expand_path("./config.ru", __dir__)
}

Rack::Server.start(options)
