# frozen_string_literal: true

source "http://rubygems.org"

# pact_broker

gem 'nokogiri', '~> 1.16', '>= 1.16.2'
gem 'pact_broker', '~> 2.109', '>= 2.109.1'
gem 'pg', '~> 1.5', '>= 1.5.5'
gem 'puma', '~> 6.4', '>= 6.4.2'
gem 'sequel', '~> 5.77'
gem 'sqlite3', '~> 1.7', '>= 1.7.2', force_ruby_platform: true
gem 'mysql2', '~> 0.5.6'
gem "rack", ">= 2.2.3", "~> 2.2" 
# gem 'rackup', '~> 2.1' # needs pact_broker to update to rack 3
