name: Ubuntu build

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, issue-1 ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
# Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
# The folder for dwarfs and other dependenies
  DEPS: deps
# Dependencies' tags
  INCBIN_TAG: 348e36b
  DWARFS_TAG: 78401c3
  RUBY_VER:   "2.6.3"
  RUBY_HASH:  "2347ed6ca5490a104ebd5684d2b9b5eefa6cd33c"
  BUNDLER_VER: "2.2.3"
  BUNDLER_HASH: "6acefda4aeb34cb3d69aff06affce10424d69f484402a9f7f5577e8c698070db"
  GDBM_VER: "1.13"
  GDBM_HASH: "9d252cbd7d793f7b12bcceaddda98d257c14f4d1890d851c386c37207000a253"
  LIBFFI_VER: "3.2.1"
  LIBFFI_HASH:"980ca30a8d76f963fca722432b1fe5af77d7a4e4d2eac5144fbc5374d4c596609a293440573f4294207e1bdd9fda80ad1e1cafb2ffb543df5a275bc3bd546483"
  NCURSES_VER: "6.2"
  NCURSES_HASH: "30306e0c76e0f9f1f0de987cf1c82a5c21e1ce6568b9227f7da5b71cbea86c9d"
  OPENSSL_VER: "1.1.0f"
  OPENSSL_HASH: "12f746f3f2493b2f39da7ecf63d7ee19c6ac9ec6a4fcd8c229da8a522cb12765"
  READLINE_VER: "7.0"
  READLINE_HASH:"750d437185286f40a369e1e4f4764eda932b9459b5ec9a731628393dd3d32334"
  YAML_VER: "0.1.7"
  YAML_HASH: "8088e457264a98ba451a90b8661fcb4f9d6f478f7265d48322a196cec2480729"
  ZLIB_VER: "1.2.11"
  ZLIB_HASH: "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1"

jobs:
  Ubuntu-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create deps folder
      run: |
        mkdir ${{github.workspace}}/${{env.DEPS}}
        type "Keys:" >> key.txt
        type  ${{ env.INCBIN_TAG }} >> key.txt
        type  ${{ env.DWARFS_TAG }} >> key.txt
        type  ${{ env.RUBY_HASH }} >> key.txt
        type  ${{ env.BUNDLER_HASH }} >> key.txt
        type  ${{ env.GDBM_HASH }} >> key.txt
        type  ${{ env.LIBFFI_HASH }} >> key.txt
        type  ${{ env.NCURSES_HASH }} >> key.txt
        type  ${{ env.OPENSSL_HASH }} >> key.txt
        type  ${{ env.READLINE_HASH }} >> key.txt
        type  ${{ env.YAML_HASH }} >> key.txt
        type  ${{ env.ZLIB_HASH }} >> key.txt
        type keys.txt

    - uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/${{env.DEPS}}
        key: ${{ github.workflow }}-${{ hashFiles('key.txt') }}-v7

    - name: Install packages Ubuntu
# Already installed: bison flex fuse3 pkg-config 
      run: |
        sudo apt-get install \
        ronn binutils-dev libarchive-dev libevent-dev libjemalloc-dev acl-dev libxml2-dev \
        libdouble-conversion-dev libiberty-dev liblz4-dev liblzma-dev libssl-dev \
        libboost-context-dev libboost-filesystem-dev libboost-program-options-dev \
        libboost-regex-dev libboost-system-dev libboost-thread-dev \
        libunwind-dev libdwarf-dev libelf-dev libfmt-dev libfuse3-dev libgoogle-glog-dev 
        
    - name: CMake Configure
      run: | 
        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}                 \
              -DDEPS:STRING=${{github.workspace}}/${{env.DEPS}}      \
              -DDWARFS_TAG:STRING=${{env.DWARFS_TAG}}                \
              -DINCBIN_TAG:STRING=${{env.INCBIN_TAG}}                \
              -B ${{github.workspace}}
                                            
    - name: CMake build and install
      run: cmake --build ${{github.workspace}} --config ${{env.BUILD_TYPE}} --target install

    - name: Create mount point
      run: |
        sudo mkdir -p /home/tebako 
        sudo chmod a+w /home/tebako
        sudo chmod g+w /home/tebako

    - name: Run
      run: sudo /usr/local/bin/tebako
